version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build: .
    ports:
      - "3000:3000"